package com.pyr.news.hib.model.scheduler;

// Generated Nov 3, 2014 6:39:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccountScheduler generated by hbm2java
 */
@Entity
@Table(name = "account_scheduler", catalog = "demo_news")
public class AccountScheduler implements java.io.Serializable {

	private AccountSchedulerId id;
	private Scheduler scheduler;

	public AccountScheduler() {
	}

	public AccountScheduler(AccountSchedulerId id, Scheduler scheduler) {
		this.id = id;
		this.scheduler = scheduler;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "accountId", column = @Column(name = "account_id", nullable = false)),
			@AttributeOverride(name = "schedulerId", column = @Column(name = "scheduler_id", nullable = false)) })
	public AccountSchedulerId getId() {
		return this.id;
	}

	public void setId(AccountSchedulerId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scheduler_id", nullable = false, insertable = false, updatable = false)
	public Scheduler getScheduler() {
		return this.scheduler;
	}

	public void setScheduler(Scheduler scheduler) {
		this.scheduler = scheduler;
	}

}
