package com.pyr.news.hib.model.scheduler;

// Generated Nov 3, 2014 6:39:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BgProcessType generated by hbm2java
 */
@Entity
@Table(name = "bg_process_type", catalog = "demo_news")
public class BgProcessType implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<BgProcess> bgProcesses = new HashSet(0);

	public BgProcessType() {
	}

	public BgProcessType(String name) {
		this.name = name;
	}

	public BgProcessType(String name, Set<BgProcess> bgProcesses) {
		this.name = name;
		this.bgProcesses = bgProcesses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bgProcessType")
	public Set<BgProcess> getBgProcesses() {
		return this.bgProcesses;
	}

	public void setBgProcesses(Set<BgProcess> bgProcesses) {
		this.bgProcesses = bgProcesses;
	}

}
