package com.pyr.news.hib.model.scheduler;

// Generated Nov 3, 2014 6:39:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BgProcessInput generated by hbm2java
 */
@Entity
@Table(name = "bg_process_input", catalog = "demo_news")
public class BgProcessInput implements java.io.Serializable {

	private Integer id;
	private String input;
	private Set<BgProcess> bgProcesses = new HashSet(0);

	public BgProcessInput() {
	}

	public BgProcessInput(String input) {
		this.input = input;
	}

	public BgProcessInput(String input, Set<BgProcess> bgProcesses) {
		this.input = input;
		this.bgProcesses = bgProcesses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "input", nullable = false, length = 65535)
	public String getInput() {
		return this.input;
	}

	public void setInput(String input) {
		this.input = input;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bgProcessInput")
	public Set<BgProcess> getBgProcesses() {
		return this.bgProcesses;
	}

	public void setBgProcesses(Set<BgProcess> bgProcesses) {
		this.bgProcesses = bgProcesses;
	}

}
