package com.pyr.news.hib.model.advertise;

// Generated Nov 3, 2014 6:31:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Advertise generated by hbm2java
 */
@Entity
@Table(name = "advertise", catalog = "demo_news")
public class Advertise implements java.io.Serializable {

	private Integer id;
	private Advertiser advertiser;
	private AdvertiseDetails advertiseDetails;
	private Date createDate;
	private Set advertiseAttachments = new HashSet(0);

	public Advertise() {
	}

	public Advertise(Advertiser advertiser, AdvertiseDetails advertiseDetails,
			Date createDate) {
		this.advertiser = advertiser;
		this.advertiseDetails = advertiseDetails;
		this.createDate = createDate;
	}

	public Advertise(Advertiser advertiser, AdvertiseDetails advertiseDetails,
			Date createDate, Set advertiseAttachments) {
		this.advertiser = advertiser;
		this.advertiseDetails = advertiseDetails;
		this.createDate = createDate;
		this.advertiseAttachments = advertiseAttachments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "createdBY", nullable = false)
	public Advertiser getAdvertiser() {
		return this.advertiser;
	}

	public void setAdvertiser(Advertiser advertiser) {
		this.advertiser = advertiser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "advertise_det_id", nullable = false)
	public AdvertiseDetails getAdvertiseDetails() {
		return this.advertiseDetails;
	}

	public void setAdvertiseDetails(AdvertiseDetails advertiseDetails) {
		this.advertiseDetails = advertiseDetails;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "advertise")
	public Set getAdvertiseAttachments() {
		return this.advertiseAttachments;
	}

	public void setAdvertiseAttachments(Set advertiseAttachments) {
		this.advertiseAttachments = advertiseAttachments;
	}

}
