package com.pyr.news.hib.model.advertise;

// Generated Nov 17, 2014 3:27:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AdvertiserAddress generated by hbm2java
 */
@Entity
@Table(name = "advertiser_address", catalog = "demo_news")
public class AdvertiserAddress implements java.io.Serializable {

	private AdvertiserAddressId id;
	private Advertiser advertiser;

	public AdvertiserAddress() {
	}

	public AdvertiserAddress(AdvertiserAddressId id, Advertiser advertiser) {
		this.id = id;
		this.advertiser = advertiser;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "advertiserId", column = @Column(name = "advertiser_id", nullable = false)),
			@AttributeOverride(name = "addressId", column = @Column(name = "address_id", nullable = false)) })
	public AdvertiserAddressId getId() {
		return this.id;
	}

	public void setId(AdvertiserAddressId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "advertiser_id", nullable = false, insertable = false, updatable = false)
	public Advertiser getAdvertiser() {
		return this.advertiser;
	}

	public void setAdvertiser(Advertiser advertiser) {
		this.advertiser = advertiser;
	}

}
