package com.pyr.news.hib.model.advertise;

// Generated Nov 3, 2014 6:31:34 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AdvertiserContact generated by hbm2java
 */
@Entity
@Table(name = "advertiser_contact", catalog = "demo_news")
public class AdvertiserContact implements java.io.Serializable {

	private AdvertiserContactId id;
	private Advertiser advertiser;

	public AdvertiserContact() {
	}

	public AdvertiserContact(AdvertiserContactId id, Advertiser advertiser) {
		this.id = id;
		this.advertiser = advertiser;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "advertiserId", column = @Column(name = "advertiser_id", nullable = false)),
			@AttributeOverride(name = "contactId", column = @Column(name = "contact_id", nullable = false)) })
	public AdvertiserContactId getId() {
		return this.id;
	}

	public void setId(AdvertiserContactId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "advertiser_id", nullable = false, insertable = false, updatable = false)
	public Advertiser getAdvertiser() {
		return this.advertiser;
	}

	public void setAdvertiser(Advertiser advertiser) {
		this.advertiser = advertiser;
	}

}
