package com.pyr.news.hib.model.advertise;

// Generated Nov 17, 2014 3:27:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Advertiser generated by hbm2java
 */
@Entity
@Table(name = "advertiser", catalog = "demo_news")
public class Advertiser implements java.io.Serializable {

	private Integer id;
	private String name;
	private String status;
	private byte frontpage;
	private Set<AdvertiserContact> advertiserContacts = new HashSet(0);
	private Set<AdvertiserAddress> advertiserAddresses = new HashSet(0);
	private Set<Advertise> advertises = new HashSet(0);

	public Advertiser() {
	}

	public Advertiser(String name, String status, byte frontpage) {
		this.name = name;
		this.status = status;
		this.frontpage = frontpage;
	}

	public Advertiser(String name, String status, byte frontpage,
			Set<AdvertiserContact> advertiserContacts, Set<AdvertiserAddress> advertiserAddresses, Set<Advertise> advertises) {
		this.name = name;
		this.status = status;
		this.frontpage = frontpage;
		this.advertiserContacts = advertiserContacts;
		this.advertiserAddresses = advertiserAddresses;
		this.advertises = advertises;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false, length = 15)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "frontpage", nullable = false)
	public byte getFrontpage() {
		return this.frontpage;
	}

	public void setFrontpage(byte frontpage) {
		this.frontpage = frontpage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "advertiser")
	public Set<AdvertiserContact> getAdvertiserContacts() {
		return this.advertiserContacts;
	}

	public void setAdvertiserContacts(Set advertiserContacts) {
		this.advertiserContacts = advertiserContacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "advertiser")
	public Set<AdvertiserAddress> getAdvertiserAddresses() {
		return this.advertiserAddresses;
	}

	public void setAdvertiserAddresses(Set<AdvertiserAddress> advertiserAddresses) {
		this.advertiserAddresses = advertiserAddresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "advertiser")
	public Set<Advertise> getAdvertises() {
		return this.advertises;
	}

	public void setAdvertises(Set<Advertise> advertises) {
		this.advertises = advertises;
	}

}
