package com.pyr.news.hib.model.advertise;

// Generated Nov 3, 2014 6:31:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AdvertiseDetails generated by hbm2java
 */
@Entity
@Table(name = "advertise_details", catalog = "demo_news")
public class AdvertiseDetails implements java.io.Serializable {

	private Integer id;
	private String shortDescription;
	private String description;
	private Set advertises = new HashSet(0);

	public AdvertiseDetails() {
	}

	public AdvertiseDetails(String description) {
		this.description = description;
	}

	public AdvertiseDetails(String shortDescription, String description,
			Set advertises) {
		this.shortDescription = shortDescription;
		this.description = description;
		this.advertises = advertises;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "short_description", length = 1000)
	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "advertiseDetails")
	public Set getAdvertises() {
		return this.advertises;
	}

	public void setAdvertises(Set advertises) {
		this.advertises = advertises;
	}

}
