package com.pyr.news.hib.model.advertise;

// Generated Nov 17, 2014 3:27:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdvertiserAddressId generated by hbm2java
 */
@Embeddable
public class AdvertiserAddressId implements java.io.Serializable {

	private int advertiserId;
	private int addressId;

	public AdvertiserAddressId() {
	}

	public AdvertiserAddressId(int advertiserId, int addressId) {
		this.advertiserId = advertiserId;
		this.addressId = addressId;
	}

	@Column(name = "advertiser_id", nullable = false)
	public int getAdvertiserId() {
		return this.advertiserId;
	}

	public void setAdvertiserId(int advertiserId) {
		this.advertiserId = advertiserId;
	}

	@Column(name = "address_id", nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdvertiserAddressId))
			return false;
		AdvertiserAddressId castOther = (AdvertiserAddressId) other;

		return (this.getAdvertiserId() == castOther.getAdvertiserId())
				&& (this.getAddressId() == castOther.getAddressId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAdvertiserId();
		result = 37 * result + this.getAddressId();
		return result;
	}

}
