package com.pyr.news.hib.model.advertise;

// Generated Nov 3, 2014 6:31:34 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdvertiseAttachmentId generated by hbm2java
 */
@Embeddable
public class AdvertiseAttachmentId implements java.io.Serializable {

	private int advertiseId;
	private int attachmentId;

	public AdvertiseAttachmentId() {
	}

	public AdvertiseAttachmentId(int advertiseId, int attachmentId) {
		this.advertiseId = advertiseId;
		this.attachmentId = attachmentId;
	}

	@Column(name = "advertise_id", nullable = false)
	public int getAdvertiseId() {
		return this.advertiseId;
	}

	public void setAdvertiseId(int advertiseId) {
		this.advertiseId = advertiseId;
	}

	@Column(name = "attachment_id", nullable = false)
	public int getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(int attachmentId) {
		this.attachmentId = attachmentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdvertiseAttachmentId))
			return false;
		AdvertiseAttachmentId castOther = (AdvertiseAttachmentId) other;

		return (this.getAdvertiseId() == castOther.getAdvertiseId())
				&& (this.getAttachmentId() == castOther.getAttachmentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAdvertiseId();
		result = 37 * result + this.getAttachmentId();
		return result;
	}

}
