package com.pyr.news.hib.model.article;

// Generated Nov 4, 2014 6:30:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArticleAttachementId generated by hbm2java
 */
@Embeddable
public class ArticleAttachementId implements java.io.Serializable {

	private int articleId;
	private int attachmentId;

	public ArticleAttachementId() {
	}

	public ArticleAttachementId(int articleId, int attachmentId) {
		this.articleId = articleId;
		this.attachmentId = attachmentId;
	}

	@Column(name = "article_id", nullable = false)
	public int getArticleId() {
		return this.articleId;
	}

	public void setArticleId(int articleId) {
		this.articleId = articleId;
	}

	@Column(name = "attachment_id", nullable = false)
	public int getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(int attachmentId) {
		this.attachmentId = attachmentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArticleAttachementId))
			return false;
		ArticleAttachementId castOther = (ArticleAttachementId) other;

		return (this.getArticleId() == castOther.getArticleId())
				&& (this.getAttachmentId() == castOther.getAttachmentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getArticleId();
		result = 37 * result + this.getAttachmentId();
		return result;
	}

}
