package com.pyr.news.hib.model.article;

// Generated Nov 4, 2014 6:30:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name = "article", catalog = "demo_news")
public class Article implements java.io.Serializable {

	private int id;
	private ArticleStory articleStory;
	private String title;
	private String headline;
	private String summary;
	private String status;
	private int createdBy;
	private String privacyLevel;
	private Integer priority;
	private byte frontpage;
	private Date modifiedAt;
	private Set keywordses = new HashSet(0);
	private Set articleReflinks = new HashSet(0);

	public Article() {
	}

	public Article(int id, String title, String headline, String status,
			int createdBy, String privacyLevel, byte frontpage, Date modifiedAt) {
		this.id = id;
		this.title = title;
		this.headline = headline;
		this.status = status;
		this.createdBy = createdBy;
		this.privacyLevel = privacyLevel;
		this.frontpage = frontpage;
		this.modifiedAt = modifiedAt;
	}

	public Article(int id, ArticleStory articleStory, String title,
			String headline, String summary, String status, int createdBy,
			String privacyLevel, Integer priority, byte frontpage,
			Date modifiedAt, Set keywordses, Set articleReflinks) {
		this.id = id;
		this.articleStory = articleStory;
		this.title = title;
		this.headline = headline;
		this.summary = summary;
		this.status = status;
		this.createdBy = createdBy;
		this.privacyLevel = privacyLevel;
		this.priority = priority;
		this.frontpage = frontpage;
		this.modifiedAt = modifiedAt;
		this.keywordses = keywordses;
		this.articleReflinks = articleReflinks;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "story_id")
	public ArticleStory getArticleStory() {
		return this.articleStory;
	}

	public void setArticleStory(ArticleStory articleStory) {
		this.articleStory = articleStory;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "headline", nullable = false)
	public String getHeadline() {
		return this.headline;
	}

	public void setHeadline(String headline) {
		this.headline = headline;
	}

	@Column(name = "summary", length = 1000)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "status", nullable = false, length = 15)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "createdBy", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "privacy_level", nullable = false, length = 29)
	public String getPrivacyLevel() {
		return this.privacyLevel;
	}

	public void setPrivacyLevel(String privacyLevel) {
		this.privacyLevel = privacyLevel;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "frontpage", nullable = false)
	public byte getFrontpage() {
		return this.frontpage;
	}

	public void setFrontpage(byte frontpage) {
		this.frontpage = frontpage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_at", nullable = false, length = 19)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "article_keywords", catalog = "demo_news", joinColumns = { @JoinColumn(name = "article_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "keyword_id", nullable = false, updatable = false) })
	public Set getKeywordses() {
		return this.keywordses;
	}

	public void setKeywordses(Set keywordses) {
		this.keywordses = keywordses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "article")
	public Set getArticleReflinks() {
		return this.articleReflinks;
	}

	public void setArticleReflinks(Set articleReflinks) {
		this.articleReflinks = articleReflinks;
	}

}
