package com.pyr.news.hib.model.article;

// Generated Nov 4, 2014 6:30:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArticleCategory generated by hbm2java
 */
@Entity
@Table(name = "article_category", catalog = "demo_news")
public class ArticleCategory implements java.io.Serializable {

	private ArticleCategoryId id;

	public ArticleCategory() {
	}

	public ArticleCategory(ArticleCategoryId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "articleId", column = @Column(name = "article_id", nullable = false)),
			@AttributeOverride(name = "categoryId", column = @Column(name = "category_id", nullable = false)) })
	public ArticleCategoryId getId() {
		return this.id;
	}

	public void setId(ArticleCategoryId id) {
		this.id = id;
	}

}
