package com.pyr.news.hib.model.article;

// Generated Nov 4, 2014 6:30:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArticleReflinkId generated by hbm2java
 */
@Embeddable
public class ArticleReflinkId implements java.io.Serializable {

	private int articleId;
	private int referenceArtId;

	public ArticleReflinkId() {
	}

	public ArticleReflinkId(int articleId, int referenceArtId) {
		this.articleId = articleId;
		this.referenceArtId = referenceArtId;
	}

	@Column(name = "article_id", nullable = false)
	public int getArticleId() {
		return this.articleId;
	}

	public void setArticleId(int articleId) {
		this.articleId = articleId;
	}

	@Column(name = "reference_artId", nullable = false)
	public int getReferenceArtId() {
		return this.referenceArtId;
	}

	public void setReferenceArtId(int referenceArtId) {
		this.referenceArtId = referenceArtId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArticleReflinkId))
			return false;
		ArticleReflinkId castOther = (ArticleReflinkId) other;

		return (this.getArticleId() == castOther.getArticleId())
				&& (this.getReferenceArtId() == castOther.getReferenceArtId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getArticleId();
		result = 37 * result + this.getReferenceArtId();
		return result;
	}

}
