package com.pyr.news.hib.model.article;

// Generated Nov 4, 2014 6:30:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArticleSection generated by hbm2java
 */
@Entity
@Table(name = "article_section", catalog = "demo_news")
public class ArticleSection implements java.io.Serializable {

	private ArticleSectionId id;

	public ArticleSection() {
	}

	public ArticleSection(ArticleSectionId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "articleId", column = @Column(name = "article_id", nullable = false)),
			@AttributeOverride(name = "sectionId", column = @Column(name = "section_id", nullable = false)) })
	public ArticleSectionId getId() {
		return this.id;
	}

	public void setId(ArticleSectionId id) {
		this.id = id;
	}

}
