package com.pyr.news.hib.model.article;

// Generated Nov 3, 2014 6:10:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArticleAttachement generated by hbm2java
 */
@Entity
@Table(name = "article_attachement", catalog = "demo_news")
public class ArticleAttachement implements java.io.Serializable {

	private ArticleAttachementId id;

	public ArticleAttachement() {
	}

	public ArticleAttachement(ArticleAttachementId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "articleId", column = @Column(name = "article_id", nullable = false)),
			@AttributeOverride(name = "attachmentId", column = @Column(name = "attachment_id", nullable = false)) })
	public ArticleAttachementId getId() {
		return this.id;
	}

	public void setId(ArticleAttachementId id) {
		this.id = id;
	}

}
