package com.pyr.news.hib.model.article;

// Generated Nov 3, 2014 6:10:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArticleReflink generated by hbm2java
 */
@Entity
@Table(name = "article_reflink", catalog = "demo_news")
public class ArticleReflink implements java.io.Serializable {

	private ArticleReflinkId id;
	private Article article;

	public ArticleReflink() {
	}

	public ArticleReflink(ArticleReflinkId id, Article article) {
		this.id = id;
		this.article = article;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "articleId", column = @Column(name = "article_id", nullable = false)),
			@AttributeOverride(name = "referenceArtId", column = @Column(name = "reference_artId", nullable = false)) })
	public ArticleReflinkId getId() {
		return this.id;
	}

	public void setId(ArticleReflinkId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reference_artId", nullable = false, insertable = false, updatable = false)
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

}
