package com.pyr.news.hib.model.article;

// Generated Nov 4, 2014 6:30:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArticleDeleteatId generated by hbm2java
 */
@Embeddable
public class ArticleDeleteatId implements java.io.Serializable {

	private int articleId;
	private Date deleteat;

	public ArticleDeleteatId() {
	}

	public ArticleDeleteatId(int articleId, Date deleteat) {
		this.articleId = articleId;
		this.deleteat = deleteat;
	}

	@Column(name = "article_id", nullable = false)
	public int getArticleId() {
		return this.articleId;
	}

	public void setArticleId(int articleId) {
		this.articleId = articleId;
	}

	@Column(name = "deleteat", nullable = false, length = 19)
	public Date getDeleteat() {
		return this.deleteat;
	}

	public void setDeleteat(Date deleteat) {
		this.deleteat = deleteat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArticleDeleteatId))
			return false;
		ArticleDeleteatId castOther = (ArticleDeleteatId) other;

		return (this.getArticleId() == castOther.getArticleId())
				&& ((this.getDeleteat() == castOther.getDeleteat()) || (this
						.getDeleteat() != null
						&& castOther.getDeleteat() != null && this
						.getDeleteat().equals(castOther.getDeleteat())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getArticleId();
		result = 37 * result
				+ (getDeleteat() == null ? 0 : this.getDeleteat().hashCode());
		return result;
	}

}
