package com.pyr.news.hib.model.article;

// Generated Nov 3, 2014 6:10:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArticleCategoryId generated by hbm2java
 */
@Embeddable
public class ArticleCategoryId implements java.io.Serializable {

	private int articleId;
	private int categoryId;

	public ArticleCategoryId() {
	}

	public ArticleCategoryId(int articleId, int categoryId) {
		this.articleId = articleId;
		this.categoryId = categoryId;
	}

	@Column(name = "article_id", nullable = false)
	public int getArticleId() {
		return this.articleId;
	}

	public void setArticleId(int articleId) {
		this.articleId = articleId;
	}

	@Column(name = "category_id", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArticleCategoryId))
			return false;
		ArticleCategoryId castOther = (ArticleCategoryId) other;

		return (this.getArticleId() == castOther.getArticleId())
				&& (this.getCategoryId() == castOther.getCategoryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getArticleId();
		result = 37 * result + this.getCategoryId();
		return result;
	}

}
