package com.pyr.news.hib.model.article;

// Generated Nov 3, 2014 6:10:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArticleDeleteat generated by hbm2java
 */
@Entity
@Table(name = "article_deleteat", catalog = "demo_news")
public class ArticleDeleteat implements java.io.Serializable {

	private ArticleDeleteatId id;

	public ArticleDeleteat() {
	}

	public ArticleDeleteat(ArticleDeleteatId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "articleId", column = @Column(name = "article_id", nullable = false)),
			@AttributeOverride(name = "deleteat", column = @Column(name = "deleteat", nullable = false, length = 19)) })
	public ArticleDeleteatId getId() {
		return this.id;
	}

	public void setId(ArticleDeleteatId id) {
		this.id = id;
	}

}
