package com.pyr.news.hib.model.article;

// Generated Nov 3, 2014 6:10:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Attachment generated by hbm2java
 */
@Entity
@Table(name = "attachment", catalog = "demo_news")
public class Attachment implements java.io.Serializable {

	private Integer id;
	private String filename;
	private String description;
	private String formatType;

	public Attachment() {
	}

	public Attachment(String filename, String formatType) {
		this.filename = filename;
		this.formatType = formatType;
	}

	public Attachment(String filename, String description, String formatType) {
		this.filename = filename;
		this.description = description;
		this.formatType = formatType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "filename", nullable = false)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "description", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "format_type", nullable = false, length = 45)
	public String getFormatType() {
		return this.formatType;
	}

	public void setFormatType(String formatType) {
		this.formatType = formatType;
	}

}
