package com.pyr.news.hib.model.acnt;

// Generated Nov 3, 2014 6:22:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "demo_news")
public class Account implements java.io.Serializable {

	private Integer id;
	private String accountTypeId;
	private String login;
	private String password;
	private String status;
	private Set userAccounts = new HashSet(0);
	private Set accountSchedulers = new HashSet(0);

	public Account() {
	}

	public Account(String accountTypeId, String login, String password,
			String status) {
		this.accountTypeId = accountTypeId;
		this.login = login;
		this.password = password;
		this.status = status;
	}

	public Account(String accountTypeId, String login, String password,
			String status, Set userAccounts, Set accountSchedulers) {
		this.accountTypeId = accountTypeId;
		this.login = login;
		this.password = password;
		this.status = status;
		this.userAccounts = userAccounts;
		this.accountSchedulers = accountSchedulers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "account_type_id", nullable = false, length = 45)
	public String getAccountTypeId() {
		return this.accountTypeId;
	}

	public void setAccountTypeId(String accountTypeId) {
		this.accountTypeId = accountTypeId;
	}

	@Column(name = "login", nullable = false)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status", nullable = false, length = 17)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set getUserAccounts() {
		return this.userAccounts;
	}

	public void setUserAccounts(Set userAccounts) {
		this.userAccounts = userAccounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set getAccountSchedulers() {
		return this.accountSchedulers;
	}

	public void setAccountSchedulers(Set accountSchedulers) {
		this.accountSchedulers = accountSchedulers;
	}

}
