package com.pyr.news.hib.model.acnt;

// Generated Nov 3, 2014 6:22:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountSchedulerId generated by hbm2java
 */
@Embeddable
public class AccountSchedulerId implements java.io.Serializable {

	private int accountId;
	private int schedulerId;

	public AccountSchedulerId() {
	}

	public AccountSchedulerId(int accountId, int schedulerId) {
		this.accountId = accountId;
		this.schedulerId = schedulerId;
	}

	@Column(name = "account_id", nullable = false)
	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	@Column(name = "scheduler_id", nullable = false)
	public int getSchedulerId() {
		return this.schedulerId;
	}

	public void setSchedulerId(int schedulerId) {
		this.schedulerId = schedulerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountSchedulerId))
			return false;
		AccountSchedulerId castOther = (AccountSchedulerId) other;

		return (this.getAccountId() == castOther.getAccountId())
				&& (this.getSchedulerId() == castOther.getSchedulerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAccountId();
		result = 37 * result + this.getSchedulerId();
		return result;
	}

}
