package com.pyr.news.hib.model.acnt;

// Generated Nov 3, 2014 6:22:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "demo_news")
public class Address implements java.io.Serializable {

	private Integer id;
	private String address1;
	private String address2;
	private String city;
	private String state;
	private String country;
	private String zip;
	private Set<UserAddresses> userAddresseses = new HashSet(0);
	private Set<EntityAddresses> entityAddresseses = new HashSet(0);

	public Address() {
	}

	public Address(String address1, String city, String state, String country,
			String zip) {
		this.address1 = address1;
		this.city = city;
		this.state = state;
		this.country = country;
		this.zip = zip;
	}

	public Address(String address1, String address2, String city, String state,
			String country, String zip, Set<UserAddresses> userAddresseses,
			Set<EntityAddresses> entityAddresseses) {
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.state = state;
		this.country = country;
		this.zip = zip;
		this.userAddresseses = userAddresseses;
		this.entityAddresseses = entityAddresseses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "address1", nullable = false)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2")
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "city", nullable = false)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", nullable = false)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", nullable = false, length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "zip", nullable = false, length = 45)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<UserAddresses> getUserAddresseses() {
		return this.userAddresseses;
	}

	public void setUserAddresseses(Set<UserAddresses> userAddresseses) {
		this.userAddresseses = userAddresseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<EntityAddresses> getEntityAddresseses() {
		return this.entityAddresseses;
	}

	public void setEntityAddresseses(Set<EntityAddresses> entityAddresseses) {
		this.entityAddresseses = entityAddresseses;
	}

}
