package com.pyr.news.hib.model.acnt;

// Generated Nov 3, 2014 6:22:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContactVia generated by hbm2java
 */
@Entity
@Table(name = "contact_via", catalog = "demo_news")
public class ContactVia implements java.io.Serializable {

	private Integer id;
	private String number;
	private String type;
	private Set userContacts = new HashSet(0);

	public ContactVia() {
	}

	public ContactVia(String number, String type) {
		this.number = number;
		this.type = type;
	}

	public ContactVia(String number, String type, Set userContacts) {
		this.number = number;
		this.type = type;
		this.userContacts = userContacts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "number", nullable = false)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "type", nullable = false, length = 17)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactVia")
	public Set getUserContacts() {
		return this.userContacts;
	}

	public void setUserContacts(Set userContacts) {
		this.userContacts = userContacts;
	}

}
