package com.pyr.news.hib.model.acnt;

// Generated Nov 3, 2014 6:22:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "demo_news")
public class Employee implements java.io.Serializable {

	private Integer id;
	private User user;
	private Employee employee;
	private Set empDpts = new HashSet(0);
	private Set empRoleses = new HashSet(0);
	private Set employees = new HashSet(0);

	public Employee() {
	}

	public Employee(User user, Employee employee) {
		this.user = user;
		this.employee = employee;
	}

	public Employee(User user, Employee employee, Set empDpts, Set empRoleses,
			Set employees) {
		this.user = user;
		this.employee = employee;
		this.empDpts = empDpts;
		this.empRoleses = empRoleses;
		this.employees = employees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mgr_id", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set getEmpDpts() {
		return this.empDpts;
	}

	public void setEmpDpts(Set empDpts) {
		this.empDpts = empDpts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set getEmpRoleses() {
		return this.empRoleses;
	}

	public void setEmpRoleses(Set empRoleses) {
		this.empRoleses = empRoleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

}
