package com.pyr.news.hib.model.acnt;

// Generated Nov 3, 2014 6:22:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entities generated by hbm2java
 */
@Entity
@Table(name = "entities", catalog = "demo_news")
public class Entities implements java.io.Serializable {

	private Integer id;
	private EntityType entityType;
	private String name;
	private String logo;
	private String supportMailId;
	private String companyMailId;
	private String status;
	private Set entityAddresseses = new HashSet(0);

	public Entities() {
	}

	public Entities(EntityType entityType, String name, String logo,
			String companyMailId, String status) {
		this.entityType = entityType;
		this.name = name;
		this.logo = logo;
		this.companyMailId = companyMailId;
		this.status = status;
	}

	public Entities(EntityType entityType, String name, String logo,
			String supportMailId, String companyMailId, String status,
			Set entityAddresseses) {
		this.entityType = entityType;
		this.name = name;
		this.logo = logo;
		this.supportMailId = supportMailId;
		this.companyMailId = companyMailId;
		this.status = status;
		this.entityAddresseses = entityAddresseses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entity_type_id", nullable = false)
	public EntityType getEntityType() {
		return this.entityType;
	}

	public void setEntityType(EntityType entityType) {
		this.entityType = entityType;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "logo", nullable = false, length = 1000)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "support_mailId")
	public String getSupportMailId() {
		return this.supportMailId;
	}

	public void setSupportMailId(String supportMailId) {
		this.supportMailId = supportMailId;
	}

	@Column(name = "company_mailId", nullable = false)
	public String getCompanyMailId() {
		return this.companyMailId;
	}

	public void setCompanyMailId(String companyMailId) {
		this.companyMailId = companyMailId;
	}

	@Column(name = "status", nullable = false, length = 17)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entities")
	public Set getEntityAddresseses() {
		return this.entityAddresseses;
	}

	public void setEntityAddresseses(Set entityAddresseses) {
		this.entityAddresseses = entityAddresseses;
	}

}
