package com.pyr.news.hib.model.acnt;

// Generated Nov 3, 2014 6:22:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EntityType generated by hbm2java
 */
@Entity
@Table(name = "entity_type", catalog = "demo_news")
public class EntityType implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set entitieses = new HashSet(0);

	public EntityType() {
	}

	public EntityType(String name) {
		this.name = name;
	}

	public EntityType(String name, Set entitieses) {
		this.name = name;
		this.entitieses = entitieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entityType")
	public Set getEntitieses() {
		return this.entitieses;
	}

	public void setEntitieses(Set entitieses) {
		this.entitieses = entitieses;
	}

}
