package com.pyr.news.hib.model.acnt;

// Generated Nov 3, 2014 6:22:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EntityAddresses generated by hbm2java
 */
@Entity
@Table(name = "entity_addresses", catalog = "demo_news")
public class EntityAddresses implements java.io.Serializable {

	private EntityAddressesId id;
	private Entities entities;
	private Address address;

	public EntityAddresses() {
	}

	public EntityAddresses(EntityAddressesId id, Entities entities,
			Address address) {
		this.id = id;
		this.entities = entities;
		this.address = address;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "entityId", column = @Column(name = "entity_id", nullable = false)),
			@AttributeOverride(name = "addressId", column = @Column(name = "address_id", nullable = false)) })
	public EntityAddressesId getId() {
		return this.id;
	}

	public void setId(EntityAddressesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entity_id", nullable = false, insertable = false, updatable = false)
	public Entities getEntities() {
		return this.entities;
	}

	public void setEntities(Entities entities) {
		this.entities = entities;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id", nullable = false, insertable = false, updatable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

}
