package com.pyr.news.hib.model.acnt;

// Generated Nov 3, 2014 6:22:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EntityAddressesId generated by hbm2java
 */
@Embeddable
public class EntityAddressesId implements java.io.Serializable {

	private int entityId;
	private int addressId;

	public EntityAddressesId() {
	}

	public EntityAddressesId(int entityId, int addressId) {
		this.entityId = entityId;
		this.addressId = addressId;
	}

	@Column(name = "entity_id", nullable = false)
	public int getEntityId() {
		return this.entityId;
	}

	public void setEntityId(int entityId) {
		this.entityId = entityId;
	}

	@Column(name = "address_id", nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EntityAddressesId))
			return false;
		EntityAddressesId castOther = (EntityAddressesId) other;

		return (this.getEntityId() == castOther.getEntityId())
				&& (this.getAddressId() == castOther.getAddressId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEntityId();
		result = 37 * result + this.getAddressId();
		return result;
	}

}
