package com.pyr.news.hib.model.acnt;

// Generated Nov 3, 2014 6:22:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "demo_news")
public class Role implements java.io.Serializable {

	private Integer id;
	private String name;
	private int roleTypeId;
	private Set<UserRoles> userRoleses = new HashSet(0);
	private Set<EmpRoles> empRoleses = new HashSet(0);

	public Role() {
	}

	public Role(String name, int roleTypeId) {
		this.name = name;
		this.roleTypeId = roleTypeId;
	}

	public Role(String name, int roleTypeId, Set<UserRoles> userRoleses, Set<EmpRoles> empRoleses) {
		this.name = name;
		this.roleTypeId = roleTypeId;
		this.userRoleses = userRoleses;
		this.empRoleses = empRoleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "role_type_id", nullable = false)
	public int getRoleTypeId() {
		return this.roleTypeId;
	}

	public void setRoleTypeId(int roleTypeId) {
		this.roleTypeId = roleTypeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<UserRoles> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRoles> userRoleses) {
		this.userRoleses = userRoleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<EmpRoles> getEmpRoleses() {
		return this.empRoleses;
	}

	public void setEmpRoleses(Set<EmpRoles> empRoleses) {
		this.empRoleses = empRoleses;
	}

}
