package com.pyr.news.hib.model.acnt;

// Generated Nov 3, 2014 6:22:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserContact generated by hbm2java
 */
@Entity
@Table(name = "user_contact", catalog = "demo_news")
public class UserContact implements java.io.Serializable {

	private UserContactId id;
	private User user;
	private ContactVia contactVia;

	public UserContact() {
	}

	public UserContact(UserContactId id, User user, ContactVia contactVia) {
		this.id = id;
		this.user = user;
		this.contactVia = contactVia;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "contactId", column = @Column(name = "contact_id", nullable = false)) })
	public UserContactId getId() {
		return this.id;
	}

	public void setId(UserContactId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_id", nullable = false, insertable = false, updatable = false)
	public ContactVia getContactVia() {
		return this.contactVia;
	}

	public void setContactVia(ContactVia contactVia) {
		this.contactVia = contactVia;
	}

}
