package com.pyr.news.hib.model.acnt;

// Generated Nov 3, 2014 6:22:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "demo_news")
public class User implements java.io.Serializable {

	private Integer id;
	private String name;
	private String firstname;
	private String lastname;
	private String email;
	private String altEmail;
	private Set<UserRoles> userRoleses = new HashSet(0);
	private Set<UserAccount> userAccounts = new HashSet(0);
	private Set<UserAddresses> userAddresseses = new HashSet(0);
	private Set<Employee> employees = new HashSet(0);
	private Set<UserContact> userContacts = new HashSet(0);

	public User() {
	}

	public User(String name, String firstname, String lastname, String email) {
		this.name = name;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
	}

	public User(String name, String firstname, String lastname, String email,
			String altEmail, Set<UserRoles> userRoleses, Set<UserAccount> userAccounts,
			Set<UserAddresses> userAddresseses, Set<Employee> employees, Set<UserContact> userContacts) {
		this.name = name;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.altEmail = altEmail;
		this.userRoleses = userRoleses;
		this.userAccounts = userAccounts;
		this.userAddresseses = userAddresseses;
		this.employees = employees;
		this.userContacts = userContacts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = true, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "firstname", nullable = false, length = 45)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 45)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "alt_email", length = 45)
	public String getAltEmail() {
		return this.altEmail;
	}

	public void setAltEmail(String altEmail) {
		this.altEmail = altEmail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserRoles> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRoles> userRoleses) {
		this.userRoleses = userRoleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserAccount> getUserAccounts() {
		return this.userAccounts;
	}

	public void setUserAccounts(Set<UserAccount> userAccounts) {
		this.userAccounts = userAccounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserAddresses> getUserAddresseses() {
		return this.userAddresseses;
	}

	public void setUserAddresseses(Set<UserAddresses> userAddresseses) {
		this.userAddresseses = userAddresseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserContact> getUserContacts() {
		return this.userContacts;
	}

	public void setUserContacts(Set<UserContact> userContacts) {
		this.userContacts = userContacts;
	}

}
