package com.pyr.news.hib.model.acnt;

// Generated Nov 3, 2014 6:22:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserContactId generated by hbm2java
 */
@Embeddable
public class UserContactId implements java.io.Serializable {

	private int userId;
	private int contactId;

	public UserContactId() {
	}

	public UserContactId(int userId, int contactId) {
		this.userId = userId;
		this.contactId = contactId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "contact_id", nullable = false)
	public int getContactId() {
		return this.contactId;
	}

	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserContactId))
			return false;
		UserContactId castOther = (UserContactId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getContactId() == castOther.getContactId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getContactId();
		return result;
	}

}
